FROM node:24-trixie-slim
ENV DEBIAN_FRONTEND=noninteractive
ENV CARGO_HOME=/opt/cargo
ENV RUSTUP_HOME=/opt/rustup
ENV PATH=/opt/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get -o Acquire::Retries=5 update \
    && cd /tmp \
    && apt-get -o Acquire::Retries=5 download ca-certificates openssl \
    && dpkg -i /tmp/openssl_*.deb /tmp/ca-certificates_*.deb \
    && rm /tmp/openssl_*.deb /tmp/ca-certificates_*.deb \
    && sed -i 's|http://deb.debian.org/debian|https://deb.debian.org/debian|g' /etc/apt/sources.list.d/debian.sources \
    && apt-get -o Acquire::Retries=5 update \
    && apt-get -o Acquire::Retries=5 install -y --no-install-recommends \
    bash ca-certificates curl file git xz-utils unzip rsync \
    build-essential pkg-config libssl-dev libgtk-3-dev libayatana-appindicator3-dev \
    librsvg2-dev libwebkit2gtk-4.1-dev patchelf \
    live-build xorriso squashfs-tools syslinux-common isolinux grub-pc-bin \
    grub-efi-amd64-bin mtools qemu-system-x86 qemu-utils ovmf expect \
    python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup.sh \
    && sh /tmp/rustup.sh -y --profile minimal \
    && rm /tmp/rustup.sh

WORKDIR /workspace
